version: '3.7'

services:
  authentication-service:
    build:
      context: server/authentication-service
      dockerfile: Dockerfile
    environment:
      - PORT=8081
      - ACTIVE_PROFILE=dev
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_SCHEMA=ecommerce_app_database
      - DB_USER=root
      - DB_PASS=secret
    ports:
      - "8081:8081"
    depends_on:
      - mysql

  common-data-service:
    build:
      context: server/common-data-service
      dockerfile: Dockerfile
    environment:
      - PORT=8082
      - ACTIVE_PROFILE=dev
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_SCHEMA=ecommerce_app_database
      - DB_USER=root
      - DB_PASS=secret
      - REDIS_HOST=redis
      - REDIS_PASSWORD=mypass
      - REDIS_PORT=6379

    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - redis

  payment-service:
    build:
      context: server/payment-service
      dockerfile: Dockerfile
    environment:
      - PORT=8083
      - ACTIVE_PROFILE=dev
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_SCHEMA=ecommerce_app_database
      - DB_USER=root
      - DB_PASS=secret
      - BASE_URL=http://localhost:8083

    ports:
      - "8083:8083"
    depends_on:
      - mysql

  search-suggestion-service:
    build:
      context: server/search-suggestion-service
      dockerfile: Dockerfile
    environment:
      - PORT=8084
      - ACTIVE_PROFILE=dev
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_SCHEMA=ecommerce_app_database
      - DB_USER=root
      - DB_PASS=secret
      - COMMON_DATA_SERVICE_URL=http://localhost:8082
    ports:
      - "8084:8084"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ecommerce_app_database
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass mypass
    environment:
      - REDIS_PASSWORD=mypass

  client:
    build:
      context: /client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_COMMON_DATA_SERVICE_PORT=8082
      - REACT_APP_AUTHENTICATION_SERVICE_PORT=8081
      - REACT_APP_SEARCH_SUGGESTION_SERVICE_PORT=8084
      - REACT_APP_PAYMENT_SERVICE_PORT=8083
      - REACT_APP_COMMON_DATA_SERVICE_URL=http://localhost:8082
      - REACT_APP_AUTHENTICATION_SERVICE_URL=http://localhost:8081
      - REACT_APP_SEARCH_SUGGESTION_SERVICE_URL=http://localhost:8084
      - REACT_APP_PAYMENT_SERVICE_URL=http://localhost:8083

    depends_on:
      - authentication-service
      - common-data-service
      - payment-service
      - search-suggestion-service

volumes:
  mysql-data:
